---
- name: Install the VMware Horizon client on RHEL
  hosts: all
  become: yes
  vars:
    dl_path: https://download3.vmware.com/software/view/viewclients/CART18FQ3
    dl_filename: VMware-Horizon-Client-4.6.0-6617224.x64.bundle
  tasks:

    - name: Download installer bundle
      get_url:
        url: "{{ dl_path }}/{{ dl_filename }}"
        dest: "/root/{{ dl_filename }}"
        mode: 0755
        owner: root
        group: root

    - name: Run the installer
      command: >-
        /usr/bin/env TERM=dumb VMWARE_EULAS_AGREED=yes
        /root/{{ dl_filename }}
        --console
        --required

    - name: Install additional packages
      yum: name={{ packages }} state=installed
      vars:
        packages:
          - atk
          - gdk-pixbuf2
          - gtk2
          - libXScrnSaver
          - libXtst
          - libgudev1
          - libxkbfile
          - xorg-x11-fonts-*
          - xorg-x11-xauth
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "6"

    - name: Install additional packages
      yum: name={{ packages }} state=installed
      vars:
        packages:
          - atk
          - gdk-pixbuf2
          - gtk2
          - libXScrnSaver
          - libgudev1
          - libpng12
          - xorg-x11-fonts-*
          - xorg-x11-xauth
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"

    - name: Create symlink for libudev.so.0
      file:
        path: /usr/lib64/libudev.so.0
        src: /usr/lib64/libgudev-1.0.so.0
        state: link
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"
...
