---
- name: Install the VMware Horizon client on RHEL
  hosts: all
  become: yes
  tasks:

    - name: Download installer bundle
      get_url:
        url: https://download3.vmware.com/software/view/viewclients/CART16Q4/VMware-Horizon-Client-4.3.0-4710754.x64.bundle
        dest: /root/VMware-Horizon-Client-4.3.0-4710754.x64.bundle
        mode: 0755
        owner: root
        group: root

    - name: Run the installer
      command: >-
        /usr/bin/env TERM=dumb VMWARE_EULAS_AGREED=yes
        /root/VMware-Horizon-Client-4.3.0-4710754.x64.bundle
        --console
        --required

    - name: Install additional packages
      yum: name={{ packages }} state=installed
      vars:
        packages:
          - xorg-x11-xauth
          - libXScrnSaver
          - atk
          - gdk-pixbuf2
          - gtk2
          - libgudev1
          - libXtst
          - xorg-x11-fonts-*
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "6"

    - name: Install additional packages
      yum: name={{ packages }} state=installed
      vars:
        packages:
          - xorg-x11-xauth
          - libpng12
          - libXScrnSaver
          - atk
          - gdk-pixbuf2
          - gtk2
          - libgudev1
          - xorg-x11-fonts-*
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"

    - name: Create symlink for libudev.so.0
      file:
        path: /usr/lib64/libudev.so.0
        src: /usr/lib64/libgudev-1.0.so.0
        state: link
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"
...
